name: grpc_client_dart
description: a people api
version: 0.6.9
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  grpc: ^3.0.2
  shelf: ^1.3.1
  shelf_router: ^1.1.3
 

dev_dependencies:
  build_runner: ^2.1.11
  build_test: ^2.1.5
  build_web_compilers: ^3.2.3
  collection: ^1.16.0